<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>arms</name>
  <version>0.1.0</version>
  <description>ROS 2 packages for manipulators available in MOBILAB</description>
  <maintainer email="nilton.csv18@edu.udesc.br">nilton</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>arms_bringup</exec_depend>
  <exec_depend>arms_utils</exec_depend>

  <!-- ARMS -->
  <exec_depend>gen3_lite_description</exec_depend>
  <exec_depend>gen3_lite_moveit_config</exec_depend>

  <exec_depend>unitree_d1_description</exec_depend>
  <exec_depend>unitree_d1_moveit_config</exec_depend>
  <exec_depend>d1_hardware_interface</exec_depend>

  <exec_depend>unitree_z1_description</exec_depend>
  <exec_depend>unitree_z1_moveit_config</exec_depend>
  <exec_depend>z1_hardware_interface</exec_depend>

  <!-- GRIPPERS -->
  <exec_depend>kinova_2f_lite_description</exec_depend>
  <exec_depend>d1_2f_description</exec_depend>
  <exec_depend>z1_1f_description</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
