joint_limits:
  joint_L:
    min_position: -0.009 # mm
    max_position: 0.033 # mm
    max_velocity: 0.02
    max_effort: 15.0
    damping: 0.7
    friction: 1.0
  joint_R:
    min_position: -0.033 # mm
    max_position: 0.009 # mm
    max_velocity: 0.02
    max_effort: 15.0
    damping: 0.7
    friction: 1.0