# This template defines controller interfaces for MoveIt
# Template variable <robot_prefix> is replaced at launch time.

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - gen3_lite_arm_controller
    - kinova_2f_lite_gripper_controller

  gen3_lite_arm_controller:
    type: FollowJointTrajectory
    joints:
      - <robot_prefix>joint_1
      - <robot_prefix>joint_2
      - <robot_prefix>joint_3
      - <robot_prefix>joint_4
      - <robot_prefix>joint_5
      - <robot_prefix>joint_6
    action_ns: follow_joint_trajectory
    default: true

  kinova_2f_lite_gripper_controller:
    type: GripperCommand
    joints:
      - <robot_prefix>right_finger_bottom_joint
    action_ns: gripper_cmd
    default: true