hardware:
  robot_ip: 1
  username:
  password:
  port:
  port_realtime:
  session_inactivity_timeout_ms:
  connection_inactivity_timeout_ms:
  tf_prefix:
  use_internal_bus_gripper_comm:
  gripper_joint_name:
  gripper_max_velocity:
  gripper_max_force: