joint_limits:
  joint_1:
    min_position: -2.68
    max_position: 2.68
    max_velocity: 1.6
    max_effort: 10.0
  joint_2:
    min_position: -2.61
    max_position: 2.61
    max_velocity: 1.6
    max_effort: 14.0
  joint_3:
    min_position: -2.61
    max_position: 2.61
    max_velocity: 1.6
    max_effort: 10.0
  joint_4:
    min_position: -2.6
    max_position: 2.6
    max_velocity: 1.6
    max_effort: 7.0
  joint_5:
    min_position: -2.53
    max_position: 2.53
    max_velocity: 1.6
    max_effort: 7.0
  joint_6:
    min_position: -2.6
    max_position: 2.6
    max_velocity: 3.2
    max_effort: 7.0